name: "Terraform Deploy from Issue"
on:
  issues:
    types: [labeled]
  
env:
  tf_actions_working_dir: ./terraform

jobs:

  permission:
    name: permission check
    runs-on: ubuntu-latest
    steps:
    - name: check permission
      id: permission_check
      if: github.event.label.name == 'approved' && github.actor == 'James-LeHa'
      run: echo Label and Permission Check Passed
    - name: check permission failed
      if: github.event.label.name != 'approved' || github.actor != 'James-LeHa'
      run: |
        echo Label and Permission Check Failed
        exit 1

  issue_ops:
    name: "Extract Issue Ops Values From Issue"
    needs: permission
    if: contains(github.event.issue.labels.*.name, 'terraform') 
    runs-on: ubuntu-latest
    outputs:
        requesting_team: ${{ steps.set_env_values.outputs.TF_VAR_requesting_team }}
        app_service_name: ${{ steps.set_env_values.outputs.TF_VAR_app_service_name }}
        location: ${{ steps.set_env_values.outputs.TF_VAR_location }}
        sku_size: ${{ steps.set_env_values.outputs.TF_VAR_sku_size }}
        sku_tier: ${{ steps.set_env_values.outputs.TF_VAR_sku_tier }}
        json_body_payload: ${{ steps.issue_body.outputs.payload }}
    
    steps:

      - name: "Checkout"
        uses: actions/checkout@master

      ### Issue Ops - Extract information from JSON - Local Action
      - name: Extract Issue Demo Specification
        id: issue_body
        uses: ./.github/actions/issue-body-parser-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}
      
      - name: Set JSON Variables as Output Values
        id: set_env_values
        run: | 
          for s in $(echo '${{ steps.issue_body.outputs.payload }}' | jq -r "to_entries|map(\"\(.key)::\(.value|tostring)\")|.[]" ); do
          echo '::set-output name='"$s"''
          done

      - name: Print JSON Variables from Issue
        run: |
          echo "The requesting Team Name: ${{ steps.set_env_values.outputs.requesting_team }}"
          echo "The requested App Service Name Size: ${{ steps.set_env_values.outputs.app_service_name }}"
          echo "The requested Location: ${{ steps.set_env_values.outputs.location }}"
          echo "The requested SKU Size: ${{ steps.set_env_values.outputs.sku_size }}"
          echo "The requested SKU Tier: ${{ steps.set_env_values.outputs.sku_tier }}"
      
    
  terraform:
    name: "Terraform Deployment From Issue"
    needs: issue_ops
    if: contains(github.event.issue.labels.*.name, 'terraform') 
    runs-on: ubuntu-latest
    ### Azure Service Principal Values
    env:
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_agent_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_agent_client_secret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_subscription_id }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_tenant_id }}
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
      
      - name: "Checkout"
        uses: actions/checkout@master

      - name: Set JSON Variables as ENV Variables
        id: set_env_values
        run: | 
          for s in $(echo '${{ needs.issue_ops.outputs.json_body_payload }}' | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
          echo "TF_VAR_"$s >> $GITHUB_ENV 
          done
        
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1.2.0
        with:
          terraform_version: 0.13.4

      - name: Terraform fmt
        id: fmt
        run: |
          terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
      
      - name: Comment TF Plan Summary
        uses: actions/github-script@v3.0.0
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Validation ü§ñ${{ steps.validate.outputs.stdout }}
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`${process.env.PLAN}\`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false -auto-approve
        continue-on-error: false
      
      - name: Comment TF Apply Summary Success
        uses: actions/github-script@v3.0.0
        if: success()
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { TF_VAR_requesting_team, TF_VAR_app_service_name } = process.env;
            const output = `#### Terraform Apply üöÄ\`${{ steps.apply.outcome }}\`

            #### Environment Summary

            * __Azure Resource Group__: ${TF_VAR_requesting_team}-rg
            * __Azure App Service Plan__: ${TF_VAR_requesting_team}-web-appservice
            * __Azure App Service Name__: ${TF_VAR_app_service_name}
            * __Actions Run:__ https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Comment TF Apply Summary Failure
        uses: actions/github-script@v3.0.0
        if: failure()
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { TF_VAR_requesting_team, TF_VAR_app_service_name } = process.env;
            const output = `#### Terraform Apply ‚ùå\`${{ steps.apply.outcome }}\`

            #### Environment Summary
            
            * __Azure Resource Group__: ${TF_VAR_requesting_team}-rg
            * __Azure App Service Plan__: ${TF_VAR_requesting_team}-web-appservice
            * __Azure App Service Name__: ${TF_VAR_app_service_name}
            * __Actions Run:__ https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
